version: "3.9"

services:
  api:
    build: ../apps/api
    container_name: ft_api
    ports:
      - "8443:8443"
    volumes:
      - ../apps/api:/app
      - ../infra/certs:/app/infra/certs:ro
      - /app/node_modules
    env_file:
      - ../apps/api/.env
    # redémarre si crash
    restart: unless-stopped
    networks:
      - transcendance
  web:
    build: ./apps/web
    container_name: ft_web
    ports:
      - "5173:5173"
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - transcendance
networks:
  transcendance:
